name: Import Crowdin translations

on:
  schedule:
    - cron: "20 16 1 * *" # Runs at 4:20 PM on the first day of every month
  workflow_dispatch:

jobs:
  import_crowdin_and_create_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Install ts-node
        run: yarn global add ts-node

      - name: Set up git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"

      - name: Fetch latest dev
        run: git fetch origin dev

      - name: Get translations
        run: npx ts-node -O '{"module":"commonjs"}' ./src/scripts/crowdin/translations/getTranslations.ts
        env:
          CROWDIN_API_KEY: ${{ secrets.CROWDIN_API_KEY }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}

      - name: Authenticate GitHub CLI
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

      - name: Process commits and post PRs by language
        run: npx ts-node -O '{"module":"commonjs"}' ./src/scripts/crowdin/translations/postLangPRs.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
